version: '3'

services:  
    Worlddb:
        image: ghusta/postgres-world-db:2.3 

    WorldService2:
        build:
            context: .
            dockerfile: Dockerfile-world3
        image: world3
        expose:
            - 8080
        ports:
            - 8080:8080
        depends_on:
            - Worlddb
                  
         